from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class RepositoryCapabilities:
    backend: str
    multi_instance_safe: bool
    transactional_outbox: bool
    advisory_locks: bool
    row_level_locking: bool


class TransactionalOutboxRepository(Protocol):
    def enqueue(self, *, topic: str, payload: dict[str, Any], dedupe_key: str | None = None) -> str: ...
    def claim_batch(self, *, limit: int = 10, lease_seconds: int = 60) -> list[dict[str, Any]]: ...
    def mark_done(self, event_id: str) -> None: ...
    def mark_failed(self, event_id: str, error: str) -> None: ...


class RepositoryFactory(Protocol):
    capabilities: RepositoryCapabilities
    def transactional_outbox(self) -> TransactionalOutboxRepository: ...
    def dual_approval_store(self) -> Any: ...
    def approval_store(self, *, ttl_seconds: int, dual_approval_store: Any | None = None) -> Any: ...
    def break_glass_store(self, *, audit_log: Any) -> Any: ...
    def webhook_security(self) -> Any: ...
    def job_queue(self) -> Any: ...
    def outbound_messages(self) -> Any: ...
    def run_store(self) -> Any: ...
    def agent_run_idempotency_store(self) -> Any: ...
    def learning_experiments(self) -> Any: ...
    def memory_store(self, privacy_config: Any | None = None) -> Any: ...
    def token_budget_manager(self, config: Any | None = None) -> Any: ...
    def model_cost_store(self) -> Any: ...
    def health_check(self) -> dict[str, Any]: ...
