#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
BAD = {"sha256:" + c * 64 for c in "0fa"}

def _valid_digest(value: str) -> bool:
    return bool(DIGEST_RE.match(value or "")) and value not in BAD and len(set(value.split(":", 1)[1])) > 1

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render Helm values.production.locked.yaml from source values and final OCI digests.")
    parser.add_argument("--source", default="deploy/kubernetes/helm/omnidesk/values.yaml")
    parser.add_argument("--output", required=True)
    parser.add_argument("--app-digest", required=True)
    parser.add_argument("--sandbox-runner-digest", required=True)
    args = parser.parse_args(argv)
    if not _valid_digest(args.app_digest):
        print("invalid app OCI digest", file=sys.stderr)
        return 64
    if not _valid_digest(args.sandbox_runner_digest):
        print("invalid sandbox-runner OCI digest", file=sys.stderr)
        return 64
    src = Path(args.source)
    text = src.read_text(encoding="utf-8")
    text = re.sub(r'(^image:\n(?:  .+\n)*?  digest:)\s*"".*$', rf'\1 "{args.app_digest}"', text, flags=re.MULTILINE)
    text = re.sub(r'(^sandboxRunner:\n(?:  .+\n)*?  digest:)\s*"".*$', rf'\1 "{args.sandbox_runner_digest}"', text, flags=re.MULTILINE)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# Generated by scripts/render_locked_helm_values.py. Do not hand edit.\n" + text, encoding="utf-8")
    print(f"wrote locked Helm values: {out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
