apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omnidesk-secrets
  namespace: omnidesk
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production-secret-store
    kind: ClusterSecretStore
  target:
    name: omnidesk-secrets
    creationPolicy: Owner
  data:
    - secretKey: OMNIDESK_ADMIN_TOKEN
      remoteRef:
        key: omnidesk/production/admin-token
    - secretKey: OMNIDESK_GATEWAY_SECRET
      remoteRef:
        key: omnidesk/production/gateway-secret
    - secretKey: OMNIDESK_APPSYNC_SECRET_PEPPER
      remoteRef:
        key: omnidesk/production/appsync-secret-pepper
    - secretKey: OMNIDESK_SANDBOX_RUNNER_TOKEN
      remoteRef:
        key: omnidesk/production/sandbox-token
    - secretKey: OMNIDESK_SANDBOX_RUNNER_HMAC_SECRET
      remoteRef:
        key: omnidesk/production/sandbox-hmac
    - secretKey: OMNIDESK_POSTGRES_DSN
      remoteRef:
        key: omnidesk/production/postgres-dsn
