apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: omnidesk-agent
  namespace: omnidesk
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: omnidesk-agent
  endpoints:
    - port: http
      path: /admin/metrics
      interval: 30s
