from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from omnidesk_agent.memory.experience import ExperienceStore


class UpgradeAnalyzer:
    """Create safe self-improvement reports from audit logs and memory.

    This level only observes and reports. It never edits code, merges branches,
    restarts services, or changes permissions.
    """

    def __init__(self, audit_log: Path, memory: ExperienceStore):
        self.audit_log = audit_log
        self.memory = memory

    def _read_audit_rows(self, limit: int = 200) -> list[dict[str, Any]]:
        if not self.audit_log.exists():
            return []
        lines = self.audit_log.read_text(encoding="utf-8", errors="replace").splitlines()[-limit:]
        rows: list[dict[str, Any]] = []
        for line in lines:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                rows.append({"raw": line})
        return rows

    def build_report(self, limit: int = 200) -> str:
        rows = self._read_audit_rows(limit=limit)
        decisions = Counter(str(r.get("decision", "unknown")) for r in rows)
        tools = Counter(str(r.get("tool", "unknown")) for r in rows)
        risks = Counter(str(r.get("risk", "unknown")) for r in rows)
        denied = [r for r in rows if r.get("decision") == "deny" or r.get("allowed") is False]
        recent_failures = self.memory.search("error OR failed OR PermissionDenied", limit=10)

        def section_counter(title: str, counter: Counter[str]) -> str:
            body = "\n".join(f"- {k}: {v}" for k, v in counter.most_common()) or "- None"
            return f"## {title}\n{body}\n"

        denied_body = "\n".join(
            f"- {r.get('tool')}.{r.get('action')} | risk={r.get('risk')} | reason={r.get('decision_reason', r.get('reason', ''))}"
            for r in denied[-20:]
        ) or "- None"
        failures_body = "\n".join(
            f"- #{item.get('id')}: {item.get('task', '')[:120]}" for item in recent_failures
        ) or "- None"

        return "\n".join([
            "# OmniDesk AI Upgrade Report",
            "",
            "This report is generated by the Level 1 self-upgrade workflow. It only analyzes logs and memory; it does not modify code.",
            "",
            section_counter("Audit Decisions", decisions),
            section_counter("Tool Usage", tools),
            section_counter("Risk Levels", risks),
            "## Recent Denied / Dry-run / Failed Actions",
            denied_body,
            "",
            "## Recent Failure-like Experience Records",
            failures_body,
            "",
            "## Suggested Next Steps",
            "- Convert repeated failures into explicit regression tests.",
            "- Prefer adding or updating `SKILL.md` for workflow knowledge before changing Python code.",
            "- For code changes, use an `ai/*` branch and require human review before merging.",
            "- Do not enable Level 4 auto-merge or auto-restart in this repository.",
            "",
        ])
